export const NEW_PROJECT = 'NEW_PROJECT';

export const ADD_PROTO_TO_PROJECT = 'ADD_PROTO_TO_PROJECT';

export const REMOVE_PROTO_FROM_PROJECT = 'REMOVE_PROTO_FROM_PROJECT';

export const SEARCH_PROTO_LIST = 'SEARCH_PROTO_LIST';

export const UPDATE_PROTO = 'UPDATE_PROTO';
